org.gradle.jvmargs=-Xmx768m -XX:+UseSerialGC -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
systemProp.java.library.path=C:/Windows/System32
