"""playIT tutor script: every spoken line and how the app joins them (DRAFT, 2026-09-30).

Single source for the line texts (generated by Kokoro) and the compositions (the order the app
plays clips in). Proposal and rationale: docs/proposals/2026-09-30-tutor-script.md.
Status: draft for the user's listening review. Nothing here is approved until the review marks it OK.

Rules (spec §2.3, Table 5; §1.4):
- A sound is never inside TTS text. Lines that contain a sound are split into fragments, and
  the app plays the fragment, then the phoneme clip ph_<L>, then the next fragment.
- No letter names anywhere in the text.
- Word mode (the echo step says the key word, AGENTS.md Decisions) adds the key word after the
  sound, "/m/ ... mouse", so the child hears the sound and the word they must say.

Composition tokens: a fragment id, "ph_{L}" (the letter's phoneme clip), "kw_{W}" (the key-word
clip), "kwslow_{W}" (the key word at slow speed), "cue_{L}" / "subcue_{L}" (per-letter cues).
"""

# id: (text, speed, source). source is the spec table the line comes from.
FRAGMENTS = {
    # Hear It carriers (Table 3)
    "car_listen":            ("Listen!", 0.9, "Table 3 step 1"),
    "car_this_letter_says":  ("This letter says...", 0.9, "Table 3 step 3"),
    "car_say_it_with_me":    ("Say it with me!", 0.9, "Table 3 step 7"),
    # Say It prompts (Table 2, Table 7)
    "car_your_turn":         ("Your turn!", 0.9, "Table 2, Table 7"),
    "car_watch_my_lips":     ("Watch my lips.", 0.85, "Table 7 attempt 2 (enlarged lip cue)"),
    "car_lets_say_together": ("Let's say it together.", 0.9, "Table 7 attempt 3"),
    # Corrections, split around the sound (§3.2)
    "fb_listen":             ("Listen:", 0.9, "Table 2 no speech; §3.2 unknown attempt"),
    "fb_letter_name":        ("That's the letter's name.", 0.9, "§3.2 letter name"),
    "fb_its_sound_is":       ("Its sound is", 0.9, "§3.2 letter name"),
    "fb_almost_just":        ("Almost! Just", 0.9, "§3.2 added vowel"),
    "fb_no_ah":              ("no 'ah.'", 0.9, "§3.2 added vowel"),
    "fb_try_later":          ("Nice try! We'll practice this one again later.", 0.9, "Table 7 attempt 3"),
    # Praise (Table 2 correct answer; §3.2 "praise names the success")
    "fb_yes":                ("Yes!", 0.9, "Table 2 correct"),
    "fb_starts_with":        ("starts with", 0.9, "word-mode praise (draft)"),
    "praise_you_did_it":     ("You did it!", 0.9, "praise for letters with no cue yet (draft)"),
    # Articulation and substitution cues
    "cue_lips_together":     ("lips together.", 0.9, "Table 2 praise cue for m"),
    "subcue_top_teeth":      ("Top teeth on your lip.", 0.9, "§3.2 /p/ for /f/"),
    # Independence (Table 2)
    "idle_reprompt":         ("Tap the ear to hear it again.", 0.9, "Table 2 idle [proposed 10 s]"),
}

# Spoken UI lines for the no-reading pass (NFR-IND-01; docs/proposals/2026-10-01-learning-ux.md).
# 8 words or fewer; never rely on color ("the big button", and the button pulses on screen).
UI_LINES = {
    "ui_hearit_next":   ("Great listening! Tap the big button.", 0.95, "card 07: Hear It next step unlocked"),
    "ui_findit_next":   ("You found them all! Tap the big button.", 0.95, "card 07: Find It complete"),
    "ui_complete_next": ("You did it! Tap the big button.", 0.95, "card 07: letter / blend complete screens"),
    "ui_node_start":    ("Tap the big button to start.", 0.95, "card 07b: map pop-up, unlocked node"),
    "ui_node_locked":   ("Finish the letters before this one first.", 0.95, "card 07b: map pop-up, locked node"),
    "ui_pick_avatar":   ("Pick your animal friend!", 0.95, "card 07b: avatar-only onboarding"),
}

# Per-letter cues. Only m (praise) and f (substitution) are written in the spec; the rest are
# [proposed] drafts listed in the proposal for teachers, and fall back as shown.
ARTICULATION_CUES = {"m": "cue_lips_together"}
SUBSTITUTION_CUES = {"f": "subcue_top_teeth", "v": "subcue_top_teeth"}   # v: [proposed]

# The app's compositions. "word" = echo step in word mode; "sound" = recall mode (pure sound).
COMPOSE = {
    "hearit_sequence":   ["car_listen", "car_this_letter_says", "ph_{L}", "PAUSE_500", "ph_{L}",
                          "PAUSE_500", "ph_{L}", "kw_{W}", "ph_{L}", "car_say_it_with_me"],
    "praise_word":       ["fb_yes", "kw_{W}", "fb_starts_with", "ph_{L}"],
    "praise_sound":      ["fb_yes", "ph_{L}", "cue_{L}"],
    "remodel_word":      ["fb_listen", "ph_{L}", "kw_{W}", "car_your_turn"],
    "remodel_sound":     ["fb_listen", "ph_{L}", "car_your_turn"],
    "corr_letter_name":  ["fb_letter_name", "fb_its_sound_is", "ph_{L}", "kw_{W}", "car_your_turn"],
    "corr_added_vowel":  ["fb_almost_just", "ph_{L}", "fb_no_ah", "kw_{W}", "car_your_turn"],
    "corr_substitution": ["fb_listen", "ph_{L}", "subcue_{L}", "kw_{W}", "car_your_turn"],
    "level2_slow":       ["car_watch_my_lips", "ph_{L}", "kwslow_{W}", "car_your_turn"],
    "level3_together":   ["car_lets_say_together", "ph_{L}", "kw_{W}", "fb_try_later"],
}
# In sound mode the kw_/kwslow_ tokens are dropped. praise_sound uses cue_{L}, or
# praise_you_did_it when the letter has no cue yet.

def expand(name, letter, word=None):
    """Composition name -> list of clip ids for one letter; drops key-word tokens when word is None."""
    out = []
    for tok in COMPOSE[name]:
        if tok.startswith(("kw_", "kwslow_")) and word is None:
            continue
        if tok == "cue_{L}":
            out.append(ARTICULATION_CUES.get(letter, "praise_you_did_it"))
            continue
        if tok == "subcue_{L}":
            if letter in SUBSTITUTION_CUES:
                out.append(SUBSTITUTION_CUES[letter])
            continue
        out.append(tok.replace("{L}", letter).replace("{W}", word or ""))
    return out
